package rendering

import (
	"bytes"
	"encoding/json"
	"fmt"
	"image"
	"image/color"
	"image/png"

	"quick-ticket/domain"

	"github.com/go-pdf/fpdf"
	"github.com/skip2/go-qrcode"
)

// RenderSpec defines the JSON structure for controlling PDF layout.
type RenderSpec struct {
	TemplateType string       `json:"template_type"`
	QRCodeConfig QRCodeConfig `json:"qr_code_config"`
	MetaFields   map[string]string `json:"meta_fields"`
	PrintLayout  *PrintLayout `json:"print_layout,omitempty"`
}

type QRCodeConfig struct {
	Page        int     `json:"page"`
	CoordinateX float64 `json:"coordinate_x"`
	CoordinateY float64 `json:"coordinate_y"`
	SizePixels  int     `json:"size_pixels"`
}

// PrintLayout defines the POS/thermal printer layout specification
// returned in API responses for client-side rendering.
type PrintLayout struct {
	CanvasDimensions struct {
		WidthMM  float64 `json:"width_mm"`
		HeightMM float64 `json:"height_mm"`
	} `json:"canvas_dimensions"`
	Elements []PrintElement `json:"elements"`
}

type PrintElement struct {
	Type          string  `json:"type"`
	Content       string  `json:"content,omitempty"`
	PayloadSource string  `json:"payload_source,omitempty"`
	FontSize      float64 `json:"font_size,omitempty"`
	Dimensions    float64 `json:"dimensions,omitempty"`
	PosXMM        float64 `json:"pos_x_mm"`
	PosYMM        float64 `json:"pos_y_mm"`
}

// FPDFRenderer implements domain.PDFRenderer using the go-pdf/fpdf library.
type FPDFRenderer struct{}

func NewFPDFRenderer() domain.PDFRenderer {
	return &FPDFRenderer{}
}

func (r *FPDFRenderer) GenerateTicketPDF(ticket *domain.Ticket, renderSpecBytes []byte) ([]byte, error) {
	spec := RenderSpec{
		TemplateType: "pdf_custom",
		QRCodeConfig: QRCodeConfig{
			Page:        1,
			CoordinateX: 140,
			CoordinateY: 680,
			SizePixels:  250,
		},
	}

	if renderSpecBytes != nil {
		if err := json.Unmarshal(renderSpecBytes, &spec); err != nil {
			return nil, fmt.Errorf("failed to parse render spec: %w", err)
		}
	}

	pdf := fpdf.New("P", "pt", "A4", "")
	pdf.AddPage()

	// ── Header ───────────────────────────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 24)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(0, 40, "TICKET", "", 1, "C", false, 0, "")

	// ── Meta Fields ──────────────────────────────────────────────────────────
	pdf.SetFont("Helvetica", "", 12)
	pdf.Ln(10)

	if spec.MetaFields != nil {
		for key, value := range spec.MetaFields {
			pdf.SetFont("Helvetica", "B", 11)
			pdf.CellFormat(150, 20, key+":", "", 0, "L", false, 0, "")
			pdf.SetFont("Helvetica", "", 11)
			pdf.CellFormat(0, 20, value, "", 1, "L", false, 0, "")
		}
	}

	pdf.Ln(5)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(100, 100, 100)
	pdf.CellFormat(0, 15, fmt.Sprintf("Ticket ID: %s", ticket.ID), "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 15, fmt.Sprintf("Status: %s", ticket.Status), "", 1, "L", false, 0, "")

	// ── Separator Line ───────────────────────────────────────────────────────
	pdf.Ln(10)
	pdf.SetDrawColor(200, 200, 200)
	pdf.Line(40, pdf.GetY(), 555, pdf.GetY())
	pdf.Ln(10)

	// ── QR Code ──────────────────────────────────────────────────────────────
	qrBytes, err := generateQRCode(ticket.SecureToken, spec.QRCodeConfig.SizePixels)
	if err != nil {
		return nil, fmt.Errorf("QR code generation failed: %w", err)
	}

	qrReader := bytes.NewReader(qrBytes)
	imgInfo := pdf.RegisterImageOptionsReader("qr_code", fpdf.ImageOptions{ImageType: "PNG"}, qrReader)
	if imgInfo == nil {
		return nil, fmt.Errorf("failed to register QR code image")
	}

	qrSizePt := float64(spec.QRCodeConfig.SizePixels) * 0.75
	pdf.ImageOptions("qr_code", spec.QRCodeConfig.CoordinateX, pdf.GetY(),
		qrSizePt, qrSizePt, false, fpdf.ImageOptions{ImageType: "PNG"}, 0, "")

	// ── Footer ───────────────────────────────────────────────────────────────
	pdf.SetY(-50)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(150, 150, 150)
	pdf.CellFormat(0, 10, "Generated by Quick Ticket BaaS", "", 1, "C", false, 0, "")
	pdf.CellFormat(0, 10, fmt.Sprintf("Secure Token: %s", ticket.SecureToken[:16]+"..."), "", 1, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("PDF output failed: %w", err)
	}

	return buf.Bytes(), nil
}

func generateQRCode(payload string, sizePx int) ([]byte, error) {
	if sizePx <= 0 {
		sizePx = 250
	}

	qr, err := qrcode.New(payload, qrcode.Medium)
	if err != nil {
		return nil, err
	}

	qrImage := qr.Image(sizePx)

	// Convert to NRGBA for consistent PNG encoding
	bounds := qrImage.Bounds()
	nrgba := image.NewNRGBA(bounds)
	for y := bounds.Min.Y; y < bounds.Max.Y; y++ {
		for x := bounds.Min.X; x < bounds.Max.X; x++ {
			r, g, b, a := qrImage.At(x, y).RGBA()
			nrgba.SetNRGBA(x, y, color.NRGBA{
				R: uint8(r >> 8),
				G: uint8(g >> 8),
				B: uint8(b >> 8),
				A: uint8(a >> 8),
			})
		}
	}

	var buf bytes.Buffer
	if err := png.Encode(&buf, nrgba); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

// BuildPrintLayout constructs the JSON print layout specification that
// clients can use for POS/thermal printer rendering.
func BuildPrintLayout(ticket *domain.Ticket, spec RenderSpec) *PrintLayout {
	layout := &PrintLayout{}
	layout.CanvasDimensions.WidthMM = 80
	layout.CanvasDimensions.HeightMM = 150

	layout.Elements = []PrintElement{
		{Type: "text", Content: "TICKET", FontSize: 14, PosXMM: 10, PosYMM: 10},
	}

	yOffset := 25.0
	for key, value := range spec.MetaFields {
		layout.Elements = append(layout.Elements, PrintElement{
			Type:     "text",
			Content:  fmt.Sprintf("%s: %s", key, value),
			FontSize: 10,
			PosXMM:   5,
			PosYMM:   yOffset,
		})
		yOffset += 8
	}

	layout.Elements = append(layout.Elements, PrintElement{
		Type:          "qrcode",
		PayloadSource: ticket.SecureToken,
		Dimensions:    40,
		PosXMM:        20,
		PosYMM:        yOffset + 5,
	})

	return layout
}
